### ISSUE TITLE
How to run JNI in Main class ?

### ISSUE THREAD

**Issue by ghost** [wpilibsuite/gradle-jni#19]
I want to run in Main class like this.

    public class HelloWorld {
    public native void print();

    static {
    System.loadLibrary("hello");
    }

    public static void main(String[] args) {
    new HelloWorld().print();
    }

    }

How to use jni libs in Main class ?

**Comment by ThadHouse** [comment]
The code in the example project would work for doing that. Theres nothing special about a main class thats different from the example.

**Comment by ghost** [comment]
How to set Native library location in gradle ?

I tried this [answer][1]. But ,  not worked.




  [1]: https://stackoverflow.com/a/23389443/16522525

**Comment by ThadHouse** [comment]
Ah, the example does not have that code, and thats generally beyond the scope of this plugin. In essence, you have to make the directory containing your jni library be pointed to by the java.library.path variable. Then the system.load command will load it.

**Comment by ghost** [comment]
I want to run in Main class.

Can you give an example code ?

**Comment by ThadHouse** [comment]
I don't really have a standalone example right now on how to do that.  I can try to throw one together if I have time in the near future.

**Comment by ghost** [comment]
How can I run in Main class in this  project?

https://github.com/wpilibsuite/gradle-jni/blob/main/example/src/main/java/jnitest/JniFunctions.java

**Comment by ThadHouse** [comment]
I don't have a sample for that right now. This plugin was designed for building libraries, not applications. It can work for applications, its just not something with current documentation on how to do so.

**Comment by ghost** [comment]
I am not asking code . I have a doubt about calling native libraries from java with Main class in this plugin.

**Comment by ghost** [comment]
I think this plugin is waste.
