### ISSUE TITLE
Plugin [id: 'edu.wpi.first.GradleJni', version: '1.0.0'] was not found in any of the following sources

### ISSUE THREAD

**Issue by ghost** [wpilibsuite/gradle-jni#22]
ERROR

    Plugin [id: 'edu.wpi.first.GradleJni',     version: '1.0.0'] was not found in any of the     following sources

  
Give a solution.

**Comment by calcmogul** [comment]
This plugin is not intended for use outside of the FIRST Robotics Competition.

**Comment by ThadHouse** [comment]
When I get a chance to work on a sample I will. Until then, this is built specifically for our internal build system, and really is not built for general consumption. Also please keep your comments to one of your existing issues, unless it's a new issue.
