### ISSUE TITLE
will this plugin helps to bundle a native library and a JNI library inside a JAR?

### ISSUE THREAD

**Issue by harideva16** [wpilibsuite/gradle-jni#24]
I have a doubt .

will this plugin helps to bundle a native library and a JNI library inside a JAR?

**Comment by ThadHouse** [comment]
This plugin does not do any packaging, that needs to be handled separately. This only assists with building. Also please keep your questions to a single issue.

**Comment by poorvajappja** [comment]
@ThadHouse okay.
