### ISSUE TITLE
Can you provide an example how to integrate this lib in kotlin dsl?

### ISSUE THREAD

**Issue by pritam-quantum-inventions** [wpilibsuite/gradle-jni#27]

**Comment by ThadHouse** [comment]
The entire gradle software model does not work in kotlin dsl. So there's no way for this to ever work in the kotlin dsl. A separate plugin could be written to support the new c++ plugins, but we have no plans currently to switch to either those or kotlin dsl. This is mostly a plugin for our internal tooling.
