### ISSUE TITLE
nm doesn't get found on PATH

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/gradle-jni#4]
If nm isn't in the same location as gcc, it doesn't get found even if it's on the path.  The usual setup for e.g. ccache is to symlink gcc and g++ from a location earlier in the PATH, but not other tools.  Currently nm is looked for only in the same folder as gcc, even if it's available later in the PATH.  The fix could be as easy as seeing if it exists in that location, and if not, using the bare name.

**Comment by ThadHouse** [comment]
This was fixed by cf3f9d08a57e77512c8dd8e09b7b75940ce41c96
