### ISSUE TITLE
minimal example project fails with "No such property: JniNativeLibrarySpec for class: org.gradle.model.ModelMap"

### ISSUE THREAD

**Issue by liblit** [wpilibsuite/gradle-jni#5]
I created a [minimal example project](https://github.com/liblit/simple-jni) in which to experiment with the Gradle JNI plugin. Unfortunately, native compilation tasks such as `components` or `model` fail due to some problem resolving `JniNativeLibrarySpec`. For example, `./gradlew model` reports:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/nobackup/liblit/joust/simple-jni/build.gradle' line: 9

* What went wrong:
Execution failed for task ':model'.
> Exception thrown while executing model rule: components { ... } @ build.gradle line 8, column 3
   > No such property: JniNativeLibrarySpec for class: org.gradle.model.ModelMap
```

Note: the [JNI pluginʼs instructions](https://github.com/wpilibsuite/gradle-jni) refer to `version '0.1.6'`, but the [latest version available from the main Gradle plugins repository](https://plugins.gradle.org/plugin/edu.wpi.first.GradleJni) is version 0.1.5, so the latter is what my minimal example project [uses](https://github.com/liblit/simple-jni/blob/d96f400355ce839ab11b9ddc27940aa4c6acdb28/build.gradle#L2). Perhaps that version mismatch is the cause of the problem? Should `JniNativeLibrarySpec` exist in release 0.1.5, or was that not added until later? Should a newer plugin release be made available in the official Gradle plugins repository?

Also on the topic of versions, I am using the latest official Gradle release: version 4.7. Is this plugin known to work with Gradle 4.7?

For the record, I am aware that my minimal example project is actually incomplete: it [declares a native method](https://github.com/liblit/simple-jni/blob/d96f400355ce839ab11b9ddc27940aa4c6acdb28/src/main/java/Main.java#L2) but provides no native implementation thereof. That is OK for now. I am learning as I go, and wanted to start with simply *declaring* the native model as per the JNI pluginʼs instructions.

**Comment by ThadHouse** [comment]
You need to apply the `cpp` plugin as well.

**Comment by ThadHouse** [comment]
Basically, the standard Gradle plugin style recommends not directly applying external project, and instead depending on the users applying themselves.

**Comment by liblit** [comment]
Thanks for the speedy reply, @ThadHouse. Unfortunately, [adding `apply plugin: 'cpp'`](https://github.com/liblit/simple-jni/commit/46bc419b01a5ffe98f9faae97332e4d441dbcecb) did not help, or at least was not sufficient. Model-related tasks still fail as before.

**Comment by ThadHouse** [comment]
Ok. I didn't realize I hadn't pushed the update that fixed that bug.

I pushed update 0.2.1. Also, I would recommend declaring all of your plugins like below, rather then the way you had it.

```
plugins {
  id 'edu.wpi.first.GradleJni' version '0.2.1'
  id 'application'
  id 'cpp'
}
```

**Comment by liblit** [comment]
Plugin version 0.2.1 fixed this problem. Excellent! Thank you for your super-speedy help, @ThadHouse.

Thanks as well for the style advice on loading plugins. I have become the main build system wrangler for [WALA](https://github.com/wala/WALA/), a large Java research project. This is the same project in which I hope to eventually put your Gradle JNI plugin to real use.  WALA has [roughly 1,300 lines of Gradle build infrastructure](https://github.com/wala/WALA/pull/278), and I learned most of whatʼs in there by trial and error. The native compilation parts were especially tricky to figure out. I expect there are many things that I could be doing better if I knew more about idiomatic Gradle style. Of course, if [someone with more Gradle experience](https://github.com/ThadHouse) wanted to look at what we are doing in WALA, and maybe contribute pull requests for any Gradle improvements, I know that the WALA maintainers are very welcoming to outside contributors.... :wink:
