### ISSUE TITLE
JNI check task fails to find matching toolchain

### ISSUE THREAD

**Issue by liblit** [wpilibsuite/gradle-jni#6]
My [simple skeleton project](https://github.com/liblit/simple-jni/) now includes a proper C implementation of its native method. This seemed like a suitable time to try the JNI check task that `enableCheckTask true` creates. Unfortunately, `./gradlew checkLibrarySharedLibraryJniSymbols` fails:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkLibrarySharedLibraryJniSymbols'.
> Failed to find a toolchain matching the binary to check
```

I am working on an Ubuntu 16.04 workstation with gcc as my native compiler and all of the other typical C/C++ development tools installed: `gcc`, `g++`, `nm`, etc. Why is Gradle failing to find a matching toolchain?

**Comment by ThadHouse** [comment]
Hmm. That should work. I'll try it out next time I can. That functionality is a bit flacky anyway, so for now I'd probably just disable it.

**Comment by ThadHouse** [comment]
In the latest release (0.9.0), this was fixed by implementing our own elf parser.
